[options]
admin_passwd = admin

db_host = False
db_port = False
db_user = odoo
db_password = odoo

db_name = NADF
dbfilter = ^NADF$

addons_path = /Users/mac/odoo17/odoo/odoo/addons,/Users/mac/odoo17/custom_addons,/Users/mac/oca_web

server_wide_modules = base,web,http_routing

log_level = info
http_port = 8071

logfile = /Users/mac/odoo_logs/nadf.log
